blogposts/views/auth.py
from flask import (
    Blueprint, render_template, request, url_for,
     redirect, flash, session, g, current_app
)
from werkzeug.security import generate_password_hash, check_password_hash
from blogposts import db
from blogposts.models.user import User
from blogposts.utils.login_manager import login_on, login_required
from blogposts.utils.httpparams import Util, Param, Filename

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=['GET', 'POST'])
@login_on
def register():
    if request.method == 'POST':
        param = Param()
        email = param.validate(request.form['email'], Util.RE_EMAIL,
            Util.ERR_EMAIL, max_length=32, field_title='e-mail')
        username = param.validate(request.form['username'], Util.RE_USERNAME,
            Util.ERR_USERNAME, max_length=16, field_title='Usuario')        
        password = param.validate(request.form['password'], Util.RE_PASSWORD,
            Util.ERR_PASSWORD, max_length=32, field_title='Contraseña')
        
        # Comprobamos la existencia del usuario        
        if User.query.filter_by(username=username).first():
            param.add_error(f'Ya existe un usario "{username}"')
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
            # Para pasarlo en la plantilla
            user = User(username, email, password)
        else:            
            # Nuevo usuario
            user = User(username, email, generate_password_hash(password))
            db.session.add(user)
            db.session.commit()            
            flash('Usuario registrado con éxito', 'info')
            return redirect(url_for('auth.login'))        
    else:
        user = None
    return render_template('auth/register.html', user=user)

@bp.route('/login', methods=['GET', 'POST'])
@login_on
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']        
        # Comprobamos la existencia del usuario
        user = User.query.filter_by(username=username).first()
        if user is None or not check_password_hash(user.password, password):
            flash('Usuario o contraseña incorrectos', 'error')           
        else:
            # Se inicia sesión y se redirige a la lista de posts
            session['user_id'] = user.id            
            return redirect(url_for('post.posts'))            
    else:
        username = ''
        password = ''
    return render_template('auth/login.html', username=username, password=password)

@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():    
    if request.method == 'POST':
        param = Param()
        check_filename = Filename()
        email = param.validate(request.form['email'], Util.RE_EMAIL,
            Util.ERR_EMAIL, max_length=32, field_title='e-mail')
        username = param.validate(request.form['username'], Util.RE_USERNAME,
            Util.ERR_USERNAME, max_length=16, field_title='Usuario')
        password = param.validate(request.form['password'], Util.RE_PASSWORD,
            Util.ERR_PASSWORD, ignore_empty=True,
            max_length=32, field_title='Contraseña')        
        file_photo = request.files['photo']     
        filename = check_filename.validate(filename=file_photo.filename,
            max_length=current_app.config.get('PROFILE_IMG_FILENAME_MAX_LEN'),
            re_ext=Util.RE_IMG_EXT, field_title='Seleccionar archivo')

        # Si el nombre de usuario cambió, comprobamos que no exista        
        if g.user.username != username:
            if User.query.filter_by(username=username).first():
                param.add_error(f'Ya existe un usario "{username}"')        
        is_error = param.is_error() or check_filename.is_error()
        if is_error:            
            # Para pasarlo en la plantilla
            user = User(username, email, password, g.user.photo)
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])            
        if check_filename.is_error():           
            for msg in check_filename.get_msgs():
                flash(msg['message'], msg['category'])
        if not is_error:
            # Actualiza el usuario
            user = User.query.get(g.user.id)
            # Si hay foto, se intenta guardar            
            if filename:
                path = f'media/{filename}'                
                file_photo.save(f'{current_app.static_folder}/{path}')
                # Guardamos en el registro la ruta relativa de la foto            
                user.photo = path
            user.email = email
            user.username = username
            if password:
                user.password = generate_password_hash(password)
            db.session.commit()
            # Actualiza los datos de sesión
            g.user = user
            flash('Perfil actualizado con éxito', 'info')                    
    else:
        user = g.user
    return render_template('auth/profile.html', user=user)

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.index'))

@bp.before_app_request
def load_session_data():    
    '''Función decorada con @bp.before_app_request para que recupere
    el usuario autenticado en la sesión en el objeto g.user, o bien
    g.user será None si no hay ningún usuario autenticado.'''    
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

blogposts/views/home.py
from flask import Blueprint, render_template, request
from blogposts.models.user import User
from blogposts.models.post import Post

bp = Blueprint('home', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        posts = search_posts(request.form['search'])
        value = 'hidden'
    else:
        posts = Post.query.all()
        value = ''
    return render_template('home/index.html', posts = posts,
        get_user=get_user, value=value)

@bp.route('/blog/<url>')
def blog(url):
    post = Post.query.filter_by(url=url).first()
    return render_template('home/blog.html', post=post, get_user=get_user)

def get_user(id):
    '''Devuelve un usuario a partir de su ID'''
    return User.query.get(id)

def search_posts(query):
    posts = Post.query.filter(Post.title.ilike(f'%{query}%')).all()    
    return posts

blogposts/templates/home/blog.html
{% extends 'base.html' %}

{% block content %}
<!-- Página de blog -->
<article class="container blog-post">
    <h1 class="blog-post-title mb-1">{% block title %}{{ post.title }}{%endblock%}</h1>
    <p class="card-text mt-3">
        {% if get_user(post.user_id).photo is none %}
        <img src="{{ url_for('static', filename='img/user-dark.png') }}" alt="mdo" width="30" class="rounded-circle">
        {% else %}
        <img src="{{ url_for('static', filename=get_user(post.user_id).photo ) }}" alt="mdo" width="30"
            class="rounded-circle">
        {% endif %}
        
        <span class="mb-1 text-muted"> <b>{{ get_user(post.user_id).username}}</b> - {{
            post.created.strftime('%d/%m/%Y %H:%M') }}</span>
    </p>

    <p class="mb-5 mt-5"> {{ post.info }} </p>
    <hr>

    <div class="mb-5 mt-5">
        {{ post.content | safe }} 
    </div>
</article>    
{% endblock %}

blogposts/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Sección de bienvenida -->
<section {{ value }}>
    <div class="row">
        <div class="col-md-6 py-1">
            <h1 class="display-4 fst-italic">
                {% block title %}Bienvenido a BLOG POSTS{% endblock %}
            </h1>
            <p>
                Aquí podrás compartir tus ideas, pensamientos y experiencias con
                una comunidad global de lectores. Nuestra plataforma es fácil de
                usar y te permite publicar tus blogs en pocos pasos.
            </p>
            <p>
                Para empezar, simplemente haz clic en el botón "Publica tu blog"
                y comienza a escribir. Puedes incluir imágenes y videos para dar
                vida a tus publicaciones y asegurarte de que sean atractivas
                para tus lectores.
            </p>
            <p>
                ¡Únete a nuestra comunidad hoy y comienza a compartir tus ideas
                con el mundo!
            </p>
            {% if not g.user %}
            <a href="{{ url_for('auth.register') }}" class="btn btn-outline-dark w-50 fs-3">
                Registrate
            </a>
            {% endif %}
        </div>
        <div class="col-md-6">
            <img src="{{ url_for('static', filename = 'img/bloguer.jpg') }}" alt="Imagen de bienvenida"
                class="img-fluid">
        </div>
    </div>
</section>
<!-- Sección de búsqueda -->
<div class="text-center">
    <div class="py-1">
        <h2 class="display-4 fst-italic">¿Buscas algo en particular?</h2>
        <div class="col-lg-6 mx-auto">
            <p class="fs-5 mb-4">
                Utiliza nuestro buscador para encontrar blogs específicos o
                temas que te interesen. Simplemente ingresa una palabra clave o
                frase y haz clic en "buscar". ¡Te sorprenderá lo fácil que es
                encontrar el contenido que buscas!
            </p>

            <div class="col container">
                <form action="{{ url_for('home.index')}}" class="d-flex" method="post">
                    <input class="form-control me-2" type="search" name="search" placeholder="Buscar"
                        aria-label="Search">
                    <button type="submit" class="btn btn-primary btn-lg">
                        Buscar
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Sección de contenido -->
<main class="py-5">
    <div class="row">
        {% for post in posts | reverse %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row
                mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <h3 class="mb-0">{{post.title}}</h3>

                    <p class="card-text mb-auto">{{ post.desc }}</p>
                    <a href="{{ url_for('home.blog', url=post.url) }}"
                        class="stretched-link">
                        Continuar leyendo
                    </a>
                    <p class="card-text mt-3">
                        {% if get_user(post.user_id).photo is none %}
                        <img src="{{ url_for('static', filename =
                            'img/user-dark.png') }}" alt="mdo" width="30"
                            class="rounded-circle">
                        {% else %}
                        <img src="{{ url_for('static', filename=
                            get_user(post.user_id).photo ) }}" alt="mdo"
                            width="30" class="rounded-circle">
                        {% endif %}
                        <span class="mb-1 text-muted"> <b>{{
                            get_user(post.user_id).username }}</b> - {{
                            post.created.strftime('%d/%m/%Y %H:%M') }}</span>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}