blogposts/models/post.py
from datetime import datetime
# Para poder manejar en MySQL un DateTime con microsegundos
from sqlalchemy.dialects.mysql import DATETIME
from blogposts import db

class Post(db.Model):
    # Nombres de tabla en plural
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    url = db.Column(db.String(128), nullable=False)
    title = db.Column(db.String(128), nullable=False)
    desc = db.Column(db.Text)
    content = db.Column(db.Text)
    # En SQLite o si no se quieren fracciones de segundo
    # created = db.Column(db.DateTime(), default=datetime.now())
    created = db.Column(DATETIME(fsp=6), default=datetime.now())

    def __init__(self, user_id, url, title, desc, content) -> None:        
        self.user_id = user_id
        self.url = url
        self.title = title
        self.desc = desc
        self.content = content

    def __repr__(self) -> str:
        return f'<Post: {self.title}>'

blogposts/views/post.py
import re
from flask import (
    Blueprint, render_template, request, url_for, redirect,
    flash, session, g, current_app
)
from blogposts import db
from blogposts.models.post import Post
from blogposts.utils.login_manager import login_required
from blogposts.utils.httpparams import Util, Param
from blogposts.utils.similwords import SimilWords

bp = Blueprint('post', __name__, url_prefix='/post')

@bp.route('/posts')
@login_required
def posts():
    posts = Post.query.all()        
    return render_template('post/posts.html', posts=posts)

@bp.route('/create', methods=['GET', 'POST'])    
@login_required
def create():
    if request.method == 'POST':
        param = Param()        
        cfg = current_app.config.get
        title = param.validate(request.form['title'], re=Util.RE_ANY_WORD_CHAR,
            msg_error='''El título tendrá al menos una letra, dígito,
            guión bajo o guión medio''', max_length=cfg('POST_TITLE_MAX_LEN'),
            field_title='Título')
        if not param.is_error() and Post.query.filter_by(title=title).first():
            param.add_error(f'El título "{title}" ya existe en otro post')
        desc = param.validate(request.form['desc'], Util.RE_STR,        
            msg_error='Descripción no admitida',
            max_length=cfg('POST_DESC_MAX_LEN'), ignore_empty=True,
            field_title='Descripción')
        content = param.validate(request.form['content'],
            Util.RE_STR, msg_error='Contenido no admitido',
            max_length=cfg('POST_CONTENT_MAX_LEN'), ignore_empty=True,
            field_title='Contenido')
        post = Post(g.user.id, SimilWords(to_lower=True).normalize(
            title, delimiter='-'), title, desc, content)
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
        else:
            db.session.add(post)
            db.session.commit()            
            flash(f'Entrada con título "{title}" creada con éxito', 'success')
    else:
        post = None
    return render_template('post/create.html', post=post)

@bp.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    post = Post.query.get(id)
    # Hay que comprobar que haya un post con ese id    
    if not post:
        flash(f'No existe ningún post el id {id}', 'warning')
        return redirect(url_for('post.posts'))
    if request.method == 'POST':
        param = Param()                
        cfg = current_app.config.get
        title = param.validate(request.form['title'], re=Util.RE_ANY_WORD_CHAR,
            msg_error='''El título tendrá al menos una letra, dígito,
            guión bajo o guión medio''', max_length=cfg('POST_TITLE_MAX_LEN'),
            field_title='Título')        
        # Hay que comprobar que el título no exista en otro post
        post_by_title = Post.query.filter_by(title=title).first()
        if not param.is_error() and post_by_title and id != post_by_title.id:            
            param.add_error(f'El título "{title}" ya existe en otro post')        
        desc = param.validate(request.form['desc'], Util.RE_STR,        
            msg_error='Descripción no admitida',
            max_length=cfg('POST_DESC_MAX_LEN'), ignore_empty=True,
            field_title='Descripción')
        content = param.validate(request.form['content'],
            Util.RE_STR, msg_error='Contenido no admitido',
            max_length=cfg('POST_CONTENT_MAX_LEN'), ignore_empty=True,
            field_title='Contenido')                
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
        else:
            post.url = SimilWords(to_lower=True).normalize(title, delimiter='-')
            post.title = title
            post.desc = desc
            post.content = content
            db.session.commit()            
            flash(f'Post actualizado con éxito', 'success')
    return render_template('post/update.html', post=post)

@bp.route('/delete/<int:id>')
@login_required
def delete(id):
    post = Post.query.get(id)
    # Hay que comprobar que haya un post con ese id    
    if post:
        db.session.delete(post)
        db.session.commit()
        flash('Post eliminado con éxito', 'success')
    else:
        flash(f'No existe ningún post el id {id}', 'warning')        
    return redirect(url_for('post.posts'))

blogposts/templates/post/create.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="header mb-4 mt-4">
        <h1 class="h3">{% block title %}Crear Blog{% endblock %}</h1>
    </div>
    <div class="body">
        <form action="{{ url_for('post.create') }}" method="post">            
            <div class="mb-3">
                <label for="title" class="form-label">Título</label>
                <input type="text" class="form-control" id="title"
                    name="title" value="{{ post.title }}"
                    placeholder="Título del blog">
            </div>
            <div class="mb-3">
                <label for="desc" class="form-label">Descripción</label>
                <textarea class="form-control" id="desc" rows="3" name="desc"
                    placeholder="Breve descripción del blog"
                    >{{ post.desc }}</textarea>
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">Contenido</label> <br>
                <textarea class="form-control" id="content" rows="7"
                    name="content" placeholder="Contenido del blog"
                    >{{ post.content }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Gurdar</button>
        </form>
    </div>
</section>
{% endblock %}

blogposts/templates/post/posts.html
{% extends 'base.html' %}

{% block content %}
<script>
    function confirmDelete(id) {
        return confirm(`¿Eliminar el post con ID = ${id}?`);        
    }
</script>
<div class="header">
    <h2 class="mb-3 mt-3">{% block title %}Tus publicaciones{% endblock %}</h2>
    <div class="d-flex justify-content-between mb-3">
        <p>¡Bienvenido al panel de administración de blogs!</p>
        <a href="{{ url_for('post.create') }}" class="btn btn-outline-success">AÑADIR BLOG</a>
    </div>
</div>
<table class=" table">
    <thead>
        <tr>
            <th class="fs-5">Título del Blog </th>
            <th colspan="2" class="fs-5">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for post in posts | reverse %}
        {% if g.user.id == post.user_id %}
        <tr>
            <td>{{ post.title }}</td>
            <td>
                <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-warning">Editar</a>
                <a href="{{ url_for('post.delete', id=post.id) }}"
                    onclick="return confirmDelete('{{ post.id }}')"
                    class="btn btn-sm btn-danger">Eliminar</a>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

blogposts/templates/post/update.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="container">
        <div class="header mb-4 mt-4">
            <h1 class="h3">{% block title %}Editar Blog{% endblock %}</h1>
        </div>
        <div class="body">
            <form action="{{ url_for('post.update', id=post.id) }}" method="post">                
                <div class="mb-3">
                    <label for="title" class="form-label">Título</label>
                    <input type="text" class="form-control" id="title"
                        name="title" required value="{{ post.title }}"
                        placeholder="Título del blog">
                </div>
                <div class="mb-3">
                    <label for="desc" class="form-label">Descripción</label>
                    <textarea class="form-control" id="desc" name="desc" rows="3"
                        placeholder="Breve descripción del blog"
                        >{{ post.desc }}</textarea>
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">Contenido</label> <br>
                    <textarea class="form-control" id="content" rows="7"
                        name="content" placeholder="Contenido del blog"
                        >{{ post.content }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}