blogposts/views/auth.py
from flask import (
    Blueprint, render_template, request, url_for,
     redirect, flash, session, g, current_app
)
from werkzeug.security import generate_password_hash, check_password_hash
from blogposts import db
from blogposts.models.user import User
from blogposts.utils.login_manager import login_on, login_required
from blogposts.utils.httpparams import Util, Param, Filename

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=['GET', 'POST'])
@login_on
def register():
    if request.method == 'POST':
        param = Param()
        email = param.validate(request.form['email'], Util.RE_EMAIL,
            Util.ERR_EMAIL, max_length=32, field_title='e-mail')
        username = param.validate(request.form['username'], Util.RE_USERNAME,
            Util.ERR_USERNAME, max_length=16, field_title='Usuario')        
        password = param.validate(request.form['password'], Util.RE_PASSWORD,
            Util.ERR_PASSWORD, max_length=32, field_title='Contraseña')
        
        # Comprobamos la existencia del usuario        
        if User.query.filter_by(username=username).first():
            param.add_error(f'Ya existe un usario "{username}"')
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
            # Para pasarlo en la plantilla
            user = User(username, email, password)
        else:            
            # Nuevo usuario
            user = User(username, email, generate_password_hash(password))
            db.session.add(user)
            db.session.commit()            
            flash('Usuario registrado con éxito', 'info')
            return redirect(url_for('auth.login'))        
    else:
        user = None
    return render_template('auth/register.html', user=user)

@bp.route('/login', methods=['GET', 'POST'])
@login_on
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']        
        # Comprobamos la existencia del usuario
        user = User.query.filter_by(username=username).first()
        if user is None or not check_password_hash(user.password, password):
            flash('Usuario o contraseña incorrectos', 'error')           
        else:
            # Se inicia sesión y se redirige a la lista de posts
            session['user_id'] = user.id            
            return redirect(url_for('post.posts'))            
    else:
        username = ''
        password = ''
    return render_template('auth/login.html', username=username, password=password)

@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():    
    if request.method == 'POST':
        param = Param()
        check_filename = Filename()
        email = param.validate(request.form['email'], Util.RE_EMAIL,
            Util.ERR_EMAIL, max_length=32, field_title='e-mail')
        username = param.validate(request.form['username'], Util.RE_USERNAME,
            Util.ERR_USERNAME, max_length=16, field_title='Usuario')
        password = param.validate(request.form['password'], Util.RE_PASSWORD,
            Util.ERR_PASSWORD, ignore_empty=True,
            max_length=32, field_title='Contraseña')        
        file_photo = request.files['photo']     
        filename = check_filename.validate(filename=file_photo.filename,
            max_length=current_app.config.get('PROFILE_IMG_FILENAME_MAX_LEN'),
            re_ext=Util.RE_IMG_EXT, field_title='Seleccionar archivo')

        # Si el nombre de usuario cambió, comprobamos que no exista        
        if g.user.username != username:
            if User.query.filter_by(username=username).first():
                param.add_error(f'Ya existe un usario "{username}"')        
        is_error = param.is_error() or check_filename.is_error()
        if is_error:            
            # Para pasarlo en la plantilla
            user = User(username, email, password, g.user.photo)
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])            
        if check_filename.is_error():           
            for msg in check_filename.get_msgs():
                flash(msg['message'], msg['category'])
        if not is_error:
            # Actualiza el usuario
            user = User.query.get(g.user.id)
            # Si hay foto, se intenta guardar            
            if filename:
                path = f'media/{filename}'                
                file_photo.save(f'{current_app.static_folder}/{path}')
                # Guardamos en el registro la ruta relativa de la foto            
                user.photo = path
            user.email = email
            user.username = username
            if password:
                user.password = generate_password_hash(password)
            db.session.commit()
            # Actualiza los datos de sesión
            g.user = user
            flash('Perfil actualizado con éxito', 'info')                    
    else:
        user = g.user
    return render_template('auth/profile.html', user=user)

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.index'))

@bp.before_app_request
def load_session_data():    
    '''Función decorada con @bp.before_app_request para que recupere
    el usuario autenticado en la sesión en el objeto g.user, o bien
    g.user será None si no hay ningún usuario autenticado.'''    
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

blogposts/views/post.py
import re
from flask import (
    Blueprint, render_template, request, url_for, redirect,
    flash, session, g, current_app
)
from blogposts import db
from blogposts.models.post import Post
from blogposts.utils.login_manager import login_required
from blogposts.utils.httpparams import Util, Param
from blogposts.utils.similwords import SimilWords

bp = Blueprint('post', __name__, url_prefix='/post')

@bp.route('/posts')
@login_required
def posts():
    posts = Post.query.all()        
    return render_template('post/posts.html', posts=posts)

@bp.route('/create', methods=['GET', 'POST'])    
@login_required
def create():
    if request.method == 'POST':
        param = Param()        
        cfg = current_app.config.get
        title = param.validate(request.form['title'], re=Util.RE_ANY_WORD_CHAR,
            msg_error='''El título tendrá al menos una letra, dígito,
            guión bajo o guión medio''', max_length=cfg('POST_TITLE_MAX_LEN'),
            field_title='Título')
        if not param.is_error() and Post.query.filter_by(title=title).first():
            param.add_error(f'El título "{title}" ya existe en otro post')
        desc = param.validate(request.form['desc'], Util.RE_STR,        
            msg_error='Descripción no admitida',
            max_length=cfg('POST_DESC_MAX_LEN'), ignore_empty=True,
            field_title='Descripción')
        content = param.validate(request.form['content'],
            Util.RE_STR, msg_error='Contenido no admitido',
            max_length=cfg('POST_CONTENT_MAX_LEN'), ignore_empty=True,
            field_title='Contenido')
        post = Post(g.user.id, SimilWords(to_lower=True).normalize(
            title, delimiter='-'), title, desc, content)
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
        else:
            db.session.add(post)
            db.session.commit()            
            flash(f'Entrada con título "{title}" creada con éxito', 'success')
    else:
        post = None
    return render_template('post/create.html', post=post)

@bp.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    post = Post.query.get(id)
    # Hay que comprobar que haya un post con ese id    
    if not post:
        flash(f'No existe ningún post el id {id}', 'warning')
        return redirect(url_for('post.posts'))
    if request.method == 'POST':
        param = Param()                
        cfg = current_app.config.get
        title = param.validate(request.form['title'], re=Util.RE_ANY_WORD_CHAR,
            msg_error='''El título tendrá al menos una letra, dígito,
            guión bajo o guión medio''', max_length=cfg('POST_TITLE_MAX_LEN'),
            field_title='Título')        
        # Hay que comprobar que el título no exista en otro post
        post_by_title = Post.query.filter_by(title=title).first()
        if not param.is_error() and post_by_title and id != post_by_title.id:            
            param.add_error(f'El título "{title}" ya existe en otro post')        
        desc = param.validate(request.form['desc'], Util.RE_STR,        
            msg_error='Descripción no admitida',
            max_length=cfg('POST_DESC_MAX_LEN'), ignore_empty=True,
            field_title='Descripción')
        content = param.validate(request.form['content'],
            Util.RE_STR, msg_error='Contenido no admitido',
            max_length=cfg('POST_CONTENT_MAX_LEN'), ignore_empty=True,
            field_title='Contenido')                
        if param.is_error():
            for msg in param.get_msgs():
                flash(msg['message'], msg['category'])
        else:
            post.url = SimilWords(to_lower=True).normalize(title, delimiter='-')
            post.title = title
            post.desc = desc
            post.content = content
            db.session.commit()            
            flash(f'Post actualizado con éxito', 'success')
    return render_template('post/update.html', post=post)

@bp.route('/delete/<int:id>')
@login_required
def delete(id):
    post = Post.query.get(id)
    # Hay que comprobar que haya un post con ese id    
    if post:
        db.session.delete(post)
        db.session.commit()
        flash('Post eliminado con éxito', 'success')
    else:
        flash(f'No existe ningún post el id {id}', 'warning')        
    return redirect(url_for('post.posts'))

blogposts/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        BlogPosts | {% block title %}{% endblock %}
    </title>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon.png') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-5.3.2/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-icons-1.11.3/font/bootstrap-icons.css') }}">
    {% block head %}{% endblock %}
</head>

<body>
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between">
                <a href="{{ url_for('home.index') }}"
                    class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{{ url_for('static', filename = 'img/bp-light.png') }}" alt="blog posts" width="40">
                </a>

                <div class="text-end">
                    {% if not g.user %}
                    <a href="{{ url_for('auth.login') }}" class="btn btn-outline-light me-2">Iniciar sesión</a>
                    <a href="{{ url_for('auth.register') }}" class="btn btn-warning">Registrate</a>
                    {% else %}
                    <a href="#" class="link-light text-decoration-none dropdown-toggle" data-bs-toggle="dropdown">
                        {% if g.user.photo is none %}
                        <img src="{{ url_for('static', filename = 'img/user-light.png') }}" alt="mdo" width="32"
                            height="32" class="rounded-circle">
                        {% else %}
                        <img src="{{ url_for('static', filename = g.user.photo) }}" alt="mdo" width="32" height="32"
                            class="rounded-circle">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li>
                            <span class="dropdown-item fw-bold">¡Hola, {{g.user.username}}!</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item d-flex align-items-center gap-2 py-2"
                                href="{{ url_for('post.create') }}">
                                <span class="d-inline-block bg-success rounded-circle p-1"></span>
                                Crear Blog
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center gap-2 py-2"
                                href="{{ url_for('post.posts') }}">
                                <span class="d-inline-block bg-primary rounded-circle p-1"></span>
                                Mis Blogs
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center gap-2 py-2"
                                href="{{ url_for('auth.profile', id = g.user.id) }}">
                                <span class="d-inline-block bg-info rounded-circle p-1"></span>
                                Perfil
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center gap-2 py-2"
                                href="{{ url_for('auth.logout') }}">
                                <span class="d-inline-block bg-danger rounded-circle p-1"></span>
                                Cerrar sesión
                            </a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="my-2 py-2">
            {% for category, message in
            get_flashed_messages(with_categories=true) %}
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="alert {{ category
                        | flash_category_to_alert_class }}
                        alert-dismissible" role="alert">
                        <div>{{ message }}</div>
                        <button type="button" class="btn-close"
                            data-bs-dismiss="alert" title="Cerrar"
                            aria-label="Close"></button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block content %}{% endblock %}
    </div>

    <footer class="text-center bg-dark text-white py-2 my-2">
        <a href="https://facite.es" target="_blank" class="text-white text-decoration-none">&copy; 2024 facite.es</a>
    </footer>

    <script src="{{ url_for('static', filename='bootstrap-5.3.2/js/bootstrap.bundle.js') }}"></script>    
</body>

</html>